### ISSUE TITLE
are there plans to provide the algorithm as a c/c++ library

### ISSUE THREAD

**Issue by inaryart** [JoonasVali/NaturalMouseMotion#15]

**Comment by JoonasVali** [comment]
No, there are no plans for that currently.

**Comment by inaryart** [comment]
> No, there are no plans for that currently.

okay, then I'll try it myself,
have you read this paper and have any comments?
https://arxiv.org/abs/2005.00890

**Comment by JoonasVali** [comment]
Go ahead. I have not read it yet :)
