### ISSUE TITLE
Can you provide the c++ version

### ISSUE THREAD

**Issue by chengpengvb** [JoonasVali/NaturalMouseMotion#16]
Thanks a lot, this is a great job, can you provide a c++ version

**Comment by JoonasVali** [comment]
Hi, thanks, unfortunately I can not provide the c++ version.

**Comment by JoonasVali** [comment]
Hello, for anyone looking a C++ version, there's someone's attempt to port it over here: https://github.com/barrybingo/CNaturalMouseMotion
