### ISSUE TITLE
How to set the time when the mouse slides to reach the target point?

### ISSUE THREAD

**Issue by LiqiNew** [JoonasVali/NaturalMouseMotion#3]
How to set the time when the mouse slides to reach the target point?

**Comment by JoonasVali** [comment]
MouseMotionFactory factory = new MouseMotionFactory(new DefaultMouseMotionNature());
DefaultSpeedManager speedManager = (DefaultSpeedManager) factory.getSpeedManager();
speedManager.setMouseMovementBaseTimeMs(500); // Approximate time
