### ISSUE TITLE
Click simulation

### ISSUE THREAD

**Issue by pihomeserver** [JoonasVali/NaturalMouseMotion#5]
Hello
Just a confirmation, the library handles the mouse movements
For clicks and drag and drop what do you use ? Java robot ?

**Comment by JoonasVali** [comment]
Not sure I completely understand what you are asking, but the library itself uses java Robot underneath by default, which is also replacable by anything else.

If you need to press any mouse button, then usual Robot mouse API will be sufficient, the library does not have a wrapper for mouse buttons as it only addresses movement.

**Comment by pihomeserver** [comment]
Thank you @joonasvali
I tried to use the standard robot function to simulate the click but then the mouse goes back to the previous location where i used the robot. So after each use of naturalmouse i have to call the move function of the robot
I guess that i am doing something wrong

**Comment by JoonasVali** [comment]
Hmm, that sounds wrong. I've never seen Robot behaving like that. I would search for logic mistakes in the code. A click should not affect position at all.

The code for a click should look something like that
```
robot.mousePress(InputEvent.BUTTON1_MASK);
Thread.sleep((int)(Math.random * 20)) 
robot.mouseRelease(InputEvent.BUTTON1_MASK);
```

If the issue persists, can you get get the Robot from the MouseMotionFactory and try that for clicking and see if it makes any difference?

This should look something like:
```
MouseMotionNature nature = factory.getNature();
DefaultSystemCalls systemCalls = (DefaultSystemCalls)nature.getSystemCalls();
Robot robot = systemCalls.getRobot();
```

**Comment by pihomeserver** [comment]
I think it's most my fault how i use the movement behaviour. Currently 2 classes : 
```
import com.github.joonasvali.naturalmouse.api.MouseMotionFactory;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.InputEvent;

public class BotMouseHandler {

    private final Robot robot = new Robot();
    private final MouseMotionFactory mouseFactory = MouseMotionFactory.getDefault();

    public BotMouseHandler() throws AWTException {
    }

    public void moveTo(int xDest, int yDest) throws InterruptedException {
        mouseFactory.move(xDest, yDest);
        robot.mouseMove(xDest, yDest);
    }

    public void leftClick() {
        robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
        robot.delay(200);
        robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
    }
}
```
And the main one : 
```
import java.awt.*;

public class App {
    public static void main(String[] args) throws AWTException, InterruptedException, AWTException {
        BotMouseHandler mh = new BotMouseHandler();

        mh.moveTo(380, 880);
        mh.leftClick();
        mh.moveTo(605, 110);
        mh.leftClick();
    }
}
```
I 'need' the instruction 'robot.mouseMove' else the click is not made at the correct position

Using NaturalMouse 2.0.2, Mac OS 10.14.6 and Java 13 in Intellij 2019.2

**Comment by pihomeserver** [comment]
Your solution works !
In the mouse handler constructor i added 
```
        MouseMotionNature nature = mouseFactory.getNature();
        SystemCalls systemCalls = new DefaultSystemCalls(robot);
        nature.setSystemCalls(systemCalls);
        mouseFactory.setNature(nature);
```

**Comment by JoonasVali** [comment]
Good to know. I think this is something I haven't yet faced and maybe a larger issue in hiding. Thanks.

**Comment by pihomeserver** [comment]
In case of : Mac OS 10.14 with Java 13
