### ISSUE TITLE
Hello, the mouse is in the automatic slide, is there an API to stop sliding?

### ISSUE THREAD

**Issue by LiqiNew** [JoonasVali/NaturalMouseMotion#6]
Hello, the mouse is in the automatic slide, is there an API to stop sliding?

**Comment by JoonasVali** [comment]
Hello, I don't understand. Can you film it or explain what is happening?

**Comment by LiqiNew** [comment]
Thank you very much for your answer. My problem is: when the mouse is already in the auto-sliding state, but he has not yet slid to the specified target point. I want to know if there is an API in this process that can prevent it from slipping.

**Comment by JoonasVali** [comment]
Ok, as I understand you want to cancel the movement of mouse once it has began. You need to `interrupt` the thread moving the mouse.

https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html
